### PR TITLE
fix: set correct local build directory

### LINKED ISSUE #335: Sources are always build completley
**Describe the bug**
Sources are always build completley

**To Reproduce**
./build.sh -t local -s ~/.ASNeG

**Expected behavior**
The sources should only be rebuilt if the build directory does not exist.

### PR DESCRIPTION
**Pull request by huebl**
Closes #335

* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] CHANGELOG have been updated (for bug fixes / features / docs)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

File: src/OpcUaProjectBuilder/ProjectTemplate/build.sh [hunk 1]
```diff
@@ -72,7 +72,7 @@ build_local()
     echo "build local start"
 
     # check build directoriy
-    if [ ! -d "build_local" ] ;
+    if [ ! -d "build_local_Debug" ] ;
```
Comment (flipback) [inline src/OpcUaProjectBuilder/ProjectTemplate/build.sh]: It is working only for Debug type. Here should be build_local_${BUILD_TYPE}
