### PR TITLE
Fix conflict DiscoveryServer URL and application EndpointURL

### LINKED ISSUE #310: OpcUaProjectBuilder3 generates a project that crashes
**Describe the bug**

If I generate a project with command

```
OpcUaProjectBuilder3 testApp TestApp 4840
```

The application fails at the start with the error:

```
$ OpcUaServer3 ~/.ASNeG3/etc/OpcUaStack/testApp/OpcUaServer.xml 
OpcUaServer3: /home/flipback/projects/ASNeG/OpcUaStack3/src/OpcUaStackCore/SecureChannel/SecureChannelBase.cpp:520: void OpcUaStackCore::SecureChannelBase::asyncWriteOpenSecureChannelRequest(OpcUaStackCore::SecureChannel *, OpcUaStackCore::OpenSecureChannelRequest &): Assertion `applicationCertificate().get() != nullptr' failed.
```

**Expected behavior**

The application must not fail.

**Logs**
[OpcUaServer.log](https://github.com/ASNeG/OpcUaStack/files/3784052/OpcUaServer.log)

**Environment (please complete the following information):**
 - Linux x64
- Version: 3.8

**Additional context**

The application works if I delete `<DiscoveryServer>` section or change port of
`<EndpointUrl>` in OpcUaServer.xml file.

### PR DESCRIPTION
**Pull request by flipback**
Closes #310

* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] CHANGELOG have been updated

* **What kind of change does this PR introduce?**

Bug fix

* **What is the new behavior (if this is a feature change)?**

1.~~The server checks if DiscoveryServer URL conflict with Application EndpointURL and exits with a message in a log.~~
2. By default, endpoint is @HOSTNAME@
3. By default, DiscoveryServer configuration is switched off

### CODE REVIEW

File: src/OpcUaServer/Server/DiscoveryClient.cpp [hunk 1]
```diff
@@ -68,6 +68,21 @@ namespace OpcUaServer
 			return false;
 		}
 
+		// check if the DiscoveryUrl matches EndPointUrls
```
Comment (huebl) [inline src/OpcUaServer/Server/DiscoveryClient.cpp]: I looked in the OPC UA specification. An OPC UA server may offer an OPC UA server and an OPC UA discovery server via the same port. Therefore, this test is not correct here. There must be another error here.

Comment (huebl) [reply src/OpcUaServer/Server/DiscoveryClient.cpp]: Question:
Where does the OPC UA server crash?

Comment (huebl) [reply src/OpcUaServer/Server/DiscoveryClient.cpp]: I think the actual problem is described in #322.

Comment (huebl) [reply src/OpcUaServer/Server/DiscoveryClient.cpp]: This Issue will not fix the actuall error.  The error can be resolved with Issue #322. For this reason, this issue and its associated PR can be closed.

Comment (flipback) [reply src/OpcUaServer/Server/DiscoveryClient.cpp]: Yes, the server crashes because the discovery client is not correct. So I described the error in #322. But I don't see any point in the configuration then the server registers itself to itself. What is why I made this PR. I agree that sever can play two roles as an application server and a discovery server at the sane time. But it must provide discovery services for other servers, not for itself.

Comment (huebl) [reply src/OpcUaServer/Server/DiscoveryClient.cpp]: There is currently no interface between the OPC UA server and the Discovery Server application. Therefore, an error is built in with this PR. An OPC UA client can no longer find the OPC UA server.

Comment (huebl) [reply src/OpcUaServer/Server/DiscoveryClient.cpp]: The OPC UA Discovery Server is provided in a separate application and in a separate git repo.

Comment (flipback) [reply src/OpcUaServer/Server/DiscoveryClient.cpp]: I've reverted the commit with the check.
